### ISSUE TITLE
Ink Feature Requests

### ISSUE THREAD

**Issue by NQNStudios** [NQNStudios/hank#10]
I want to keep all requests for missing Ink features in one place. If there's something Ink can do that you want Hank to do, write it in this thread for discussion.

For example, Hank currently does not support stitches within knots, or sections starting with `===`, so you might request one of those too be added here.

Note that features of embedded scripting in Ink will likely never be added, because Hank stories will already have access to the Haxe language & standard library, making implementing Ink's embedded scripting redundant.

**Comment by zicklag** [comment]
I have been writing my first Ink story over the last couple of days and the features that I use that are not yet in Hank are:

1. Stitches inside of Knots, like you already mentioned
2. Alternatives, like in the Ink [tutorial](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#types-of-alternatives).
3. [Conditional blocks](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#3-conditional-blocks-ifelse).
4. [Labeling options and gathers](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#gathers-and-options-can-be-labelled).
5. An IDE. It would be great if we could create something like Inky IDE inside of VSCode ( and write it in Haxe :wink: ).

I really want to get my game running on Hank and I might work on some of these features. If we get these features in, I think we would be in really good shape.

**Comment by NQNStudios** [comment]
Maybe it was a mistake to try and group these things together -- I'll turn them back into separate issues for cleaner discussion :)

**Comment by NQNStudios** [comment]
> I really want to get my game running on Hank and I might work on some of these features. If we get these features in, I think we would be in really good shape.

@zicklag you should know that I'm using my winter break free time for this project, but once my next semester starts I really can't guarantee continued support! Beware if you intend to make this a dependency for a serious project.

**Comment by zicklag** [comment]
@NQNStudios Don't worry, I have a similar situation. Most things I do deserves a similar disclaimer. :wink:
