### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by NQNStudios** [NQNStudios/hank#12]
https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#sequences-cycles-and-other-alternatives

**Comment by zicklag** [comment]
I see your point, and I think that makes sense. Then we could just expose those functions in HScript without needing to change anything about the current implementation. That's a plus.

Still, there are a couple things I don't like about it:
* You have to put your strings inside quotes for those functions, which means having to do escapes and things like that if you've got quotes inside of the strings. ( not a huge deal )
* I don't think that would very well with nested alternatives. Obviously you can achieve the same effect in other ways, but you would have to write more Haxe which works against the average user that you want to be able to write hank.

**Comment by NQNStudios** [comment]
After looking over the Ink tutorial again, I see that you're right--the sleek syntax for alternative sequences is pretty great. I think I'll refactor `fillHExpressions()` into a method `fillBracketExpressions()` which calls two separate functions depending on whether the bracket contents start with the symbol for an alternative sequence, or not, in which case it will be parsed as hscript like before. I'm planning to allow the single-character symbols Ink uses, and also versions like 'shuffle' for a shuffle, etc. if the author wants more readability.

**Comment by NQNStudios** [comment]
Two specifications from `WritingWithInk.md` that I predict will require careful attention:

> Alternatives can be nested.
>
> The Ratbear {&{wastes no time and |}swipes|scratches} {&at you|into your {&leg|arm|cheek}}.
>
> Alternatives can include divert statements.

> I {waited.|waited some more.|snoozed.|woke up and waited more.|gave up and left. -> leave_post_office}

**Comment by NQNStudios** [comment]
Turn this example into a testing example: https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#examples

**Comment by NQNStudios** [comment]
Closed by 088c22d715234f19ccd2f156210465fb11020e6c. Let me know if there are any problems.
