### ISSUE TITLE
[FYI] Type Definitions Don't Work in HScript

### ISSUE THREAD

**Issue by zicklag** [NQNStudios/hank#16]
https://github.com/NQNStudios/hank/blob/b8c6eca1e1ba06c661d79a1efa4cce37ad4fb41b/examples/TheIntercept.hank#L25

FYI, there are no type definitions of any kind in HScript ( see [limitations](https://github.com/HaxeFoundation/hscript#limitations) ). I just saw your comment, so I thought I'd mention it.

**Comment by NQNStudios** [comment]
I saw that. Kind of disappointing--I wonder if you can even important types? Like, what if I wanted to have complex enums in my Hank script and use pattern matching?

I know there are some forks that extend hscript, which might be worth looking into.

**Comment by zicklag** [comment]
It might be better to implement that in the language itself. I know you said you kind of lean away from hacking the language, but I think it is going to be necessary to add language features if we don't want to have you writing a bunch of Haxe for the story logic. I'm not 100% sure or anything, but that is my initial thought.

Your exercise of porting that Ink game could be a good test to see how things will play out and what design decisions you might want to make.

**Comment by NQNStudios** [comment]
The last thing I wanted to check was whether functions can be defined within hscript, which it very luckily turns out they can. (Just without typed arguments.) I think core hscript without type declarations is good enough for any ink dev's purposes, so I'm closing this.
