### ISSUE TITLE
More powerful embedded Haxe

### ISSUE THREAD

**Issue by NQNStudios** [NQNStudios/hank#43]
I think it would be useful to have some Haxe features that hscript is missing, such as ~~function and~~ enum definitions especially, and the ability to invoke constructors and static methods.

So I'll be looking into forks/extensions/alternatives to hscript. The first one I checked out was ihx, which won't work because it depends on the system's Haxe and Neko binaries (which means it's not fully portable/cross-platform).

Edit: I was wrong. function definitions are allowed in hscript.

**Comment by NQNStudios** [comment]
A few things slipped my mind about what is/isn't possible in hscript. We previously discussed some of them in issue #16 and here's the link to hscript's limitations: https://github.com/HaxeFoundation/hscript#limitations. Best not to forget the details before making any big decisions.

**Comment by NQNStudios** [comment]
Also very important: https://github.com/HaxeFoundation/hscript#advanced-usage

What I'm trying to figure out now is if I can use Haxe macros to reimplement some of the janky code translations I've done in `evaluateHaxeExpression()` in saner ways.

**Comment by NQNStudios** [comment]
Hscript contains the function `Macro.convert(e: hscript.Expr): Expr`. What we need to make this possible is a reverse conversion, `convert(e: haxe.macro.Expr): hscript.Expr`. Then, we'll have access to the full suite of haxe expression reification tools in order to transmute embedded Haxe.

However, it might be simpler to attempt expression reification on hscript Expr's directly, rather than implement the reverse conversion.

**Comment by NQNStudios** [comment]
To take the simpler approach (using hscript Expr objects only) it seems the main transmutations would be trivial:

`EVar(name, type, expression)` tells the HInterface to` declare a variable with that name in interp.variables, and change to `EBinop(=, EIdent(name), expression)`

`EIdent(varname)` can be transmuted to check if the varname refers to a viewcount

`EBinop(&&, EIdent(varname), EIdent(varname2))` allows for &&'ing view counts as if they were bools, like the TODO comment [here](https://github.com/NQNStudios/hank/blob/afaed1826587e8868b737bcc025a4d399464b8e9/hank/Story.hx#L1023) notes is currently impossible

**Comment by NQNStudios** [comment]
One thing I want to do that *would* require haxe macros is the idea of wrapping static classes like `FlxG` in instances that can be passed to interp.variables. I think that that conversion doesn't need to happen at runtime, though, it can happen at compiletime for a Hankerchief game.

**Comment by zicklag** [comment]
Just found this and thought I'd point it out. Might be useful. :man_shrugging: 

https://github.com/darmie/hxComposer

**Comment by NQNStudios** [comment]
That actually does look useful! The documentation is sparse/confusing but what I glean from the code looks nifty. I might spend some time in the next month or so looking it over.

**Comment by NQNStudios** [comment]
triaging this for now
